/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppFdRouteImport } from './routes/_app.fd'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCheckRouteImport } from './routes/_app.check'
import { Route as AppBanksRouteImport } from './routes/_app.banks'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppFdRoute = AppFdRouteImport.update({
  id: '/fd',
  path: '/fd',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckRoute = AppCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksRoute = AppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/banks': typeof AppBanksRoute
  '/check': typeof AppCheckRoute
  '/dashboard': typeof AppDashboardRoute
  '/fd': typeof AppFdRoute
  '/loans': typeof AppLoansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/banks': typeof AppBanksRoute
  '/check': typeof AppCheckRoute
  '/dashboard': typeof AppDashboardRoute
  '/fd': typeof AppFdRoute
  '/loans': typeof AppLoansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/banks': typeof AppBanksRoute
  '/_app/check': typeof AppCheckRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fd': typeof AppFdRoute
  '/_app/loans': typeof AppLoansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/banks'
    | '/check'
    | '/dashboard'
    | '/fd'
    | '/loans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/banks'
    | '/check'
    | '/dashboard'
    | '/fd'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/banks'
    | '/_app/check'
    | '/_app/dashboard'
    | '/_app/fd'
    | '/_app/loans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fd': {
      id: '/_app/fd'
      path: '/fd'
      fullPath: '/fd'
      preLoaderRoute: typeof AppFdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/check': {
      id: '/_app/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof AppCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks': {
      id: '/_app/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AppBanksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBanksRoute: typeof AppBanksRoute
  AppCheckRoute: typeof AppCheckRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFdRoute: typeof AppFdRoute
  AppLoansRoute: typeof AppLoansRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBanksRoute: AppBanksRoute,
  AppCheckRoute: AppCheckRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFdRoute: AppFdRoute,
  AppLoansRoute: AppLoansRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
